sudo: false
os:
  - linux

language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libelf-dev
      - libdw-dev
      - binutils-dev

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test
after_success:
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - travis-cargo coveralls --no-sudo --verify
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --include-pattern=/src target/kcov target/debug/seek_bufread-*; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUST_BACKTRACE=1
