sudo: false

language: rust
cache: cargo
os:
  - linux

env:
  - RUST_BACKTRACE=1

rust:
    - stable
    - beta
    - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libelf-dev
      - libdw-dev
      - binutils-dev

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo clean &&
      travis-cargo build &&
      travis-cargo test
after_success:
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]] \
        && (! rustc --version | grep -q -E 'beta|nightly')
    then
        travis-cargo coveralls --no-sudo --verify # (can) fails
        # NOTE: doc tests aren't included
        KCOV=./kcov/build/src/kcov ./scripts/coverage.sh
    fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUST_BACKTRACE=1
